#!/usr/bin/env node
// ---------------------------------------------------------------------------
// Erzeugt den mitgelieferten Schema-Fallback aus einem vollstaendigen
// CMDB-Schema-Dump der FortiGate.
//
// Der Rohdump hat rund 4 MB und 685 Tabellen; gebraucht werden sieben. Das
// Ergebnis liegt bei etwa 110 KB und wandert ins Repo und ins Image.
//
// Dump erzeugen:
//   curl -k -H "Authorization: Bearer <token>" \
//     "https://<fortigate>/api/v2/cmdb/?action=schema" -o api-doku.json
//
// Aufruf:
//   node scripts/trim-schema.mjs [quelle] [ziel]
// ---------------------------------------------------------------------------
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const src = resolve(process.argv[2] ?? join(root, 'api-doku.json'));
const dst = resolve(process.argv[3] ?? join(root, 'server', 'schema-fallback.json'));

/** Muss zu TABLES in server/schema.js passen. */
const KEEP = [
  ['switch-controller', 'dynamic-port-policy'],
  ['switch-controller', 'vlan-policy'],
  ['switch-controller', 'lldp-profile'],
  ['switch-controller', 'switch-interface-tag'],
  ['switch-controller.qos', 'qos-policy'],
  ['switch-controller.security-policy', '802-1X'],
  ['switch-controller', 'managed-switch'],
];

// Von managed-switch nur die Felder, die die Suite anfasst – der volle Baum
// macht allein mehrere hundert Kilobyte aus.
const MANAGED_SWITCH_KEEP = ['switch-id', 'sn', 'description', 'type', 'ports'];
const PORT_KEEP = [
  'port-name', 'description', 'status', 'access-mode', 'port-policy',
  'matched-dpp-policy', 'matched-dpp-intf-tags', 'interface-tags', 'vlan',
  'allowed-vlans', 'untagged-vlans', 'allowed-vlans-all', 'poe-status',
  'lldp-profile', 'qos-policy', 'port-security-policy', 'learning-limit', 'sticky-mac',
];

if (!existsSync(src)) {
  console.error(`No schema dump at ${src}\nPass the path as the first argument.`);
  process.exit(1);
}

const dump = JSON.parse(readFileSync(src, 'utf8'));
const results = [];
const missing = [];

for (const [path, name] of KEEP) {
  const entry = dump.results?.find((r) => r.path === path && r.name === name);
  if (!entry) {
    missing.push(`${path}/${name}`);
    continue;
  }
  results.push(name === 'managed-switch' ? { ...entry, schema: trimManagedSwitch(entry.schema) } : entry);
}

function trimManagedSwitch(schema) {
  const children = {};
  for (const k of MANAGED_SWITCH_KEEP) {
    const c = schema.children?.[k];
    if (!c) continue;
    if (k === 'ports') {
      const pc = {};
      for (const pk of PORT_KEEP) if (c.children?.[pk]) pc[pk] = c.children[pk];
      children[k] = { ...c, children: pc };
    } else {
      children[k] = c;
    }
  }
  return { ...schema, children };
}

if (missing.length) {
  console.error(`Missing from the dump: ${missing.join(', ')}`);
  console.error('Is this a full "?action=schema" dump of a FortiGate with switch-controller support?');
  process.exit(1);
}

// Seriennummer und VDOM des Quellgeraets gehoeren nicht in ein oeffentliches Repo.
const out = {
  _note: 'Trimmed CMDB schema used as offline fallback. Generated by scripts/trim-schema.mjs.',
  version: dump.version ?? null,
  build: dump.build ?? null,
  results,
};

writeFileSync(dst, JSON.stringify(out), 'utf8');

const kb = (n) => `${Math.round(n / 1024)} KB`;
console.log(`${kb(readFileSync(src).length)} (${dump.results.length} tables)  ->  ${kb(readFileSync(dst).length)} (${results.length} tables)`);
console.log(`FortiOS ${out.version} build ${out.build}  ->  ${dst}`);
